### ISSUE TITLE
Scenario Outline tests don't replace placeholders in title

### ISSUE THREAD

**Issue by stenaksel** [YouneselBarnoussi/vscode-BDD-Python-test-adapter#4]
Given a Scenario Outline with a <placeholder> in its title
When running the example table rows as a tests 
Then the title of the test (of the running example table row) should have updated the placeholder from the table rows data
And the number of rows in the example table should equal the number of tests run

So this scenario outline with example:
```
        Scenario Outline: Compute the fibonacci sequence for <count> integers
            Given a count of "<count>"
             When I call the fib function
             Then it should return a sequence "<sequence>"

        Examples: Counts
            | count | sequence      |
            | 2     | 1, 1          |
            | 5     | 1, 1, 2, 3, 5 |

```
Should result in these two test:
       `Compute the fibonacci sequence for 2 integers`
       `Compute the fibonacci sequence for 5 integers`

Today it only show 
       `Compute the fibonacci sequence for <count> integers`

**Comment by YouneselBarnoussi** [comment]
Would you be able to test this again with version `1.0.0` as I don't have this issue with this. It shows it twice or me in the list.

```
    Scenario Outline: The printer will go in Error state when an invalid <filename> document is provided
        Given a printer in operating mode
        When I create an invalid file named '<filename>'
        And I add the '<filename>' file to the printer queue
        Then the printer is in '<state>' state
        Examples:
            | filename                  | state |
            | no_extension              | ERROR |
            | unsupported_extension.abc | ERROR |
```
![image](https://user-images.githubusercontent.com/16510310/212131307-44667ba9-d07d-4602-a71c-e913b9263874.png)
