### ISSUE TITLE
Getting Started - where are my tests

### ISSUE THREAD

**Issue by andez2000** [YouneselBarnoussi/vscode-BDD-Python-test-adapter#6]
I have VSCode installed on Windows 10:

```
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

I have a folder opened in VSCode containing my project with a `venv` setup to run my code against.  At the moment I have created a feature file and step file with a simple Given When Then.

When I activate the venv and run the tests by running `behave`, I get the output in the terminal.

```
(.venv) PS C:\dev\code\playground\behave\app> behave
Feature: Foo # features/my_feature.feature:1

  Scenario: Foo  # features/my_feature.feature:3
    Given Plop   # features/steps/my_feature_steps.py:4
    When Ploop   # features/steps/my_feature_steps.py:8
    Then Ploooop # features/steps/my_feature_steps.py:12

1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
3 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.000s
(.venv) PS C:\dev\code\playground\behave\app>
```

My project looks like this:

```
├───.vscode
│       settings.json
│       
└───app
    │   main.py
    │   requirements.txt
    │           
    └───features
        │   my_feature.feature
        │   
        └───steps
                my_feature_steps.py
```

## venv packages

```pip
behave==1.2.6
parse==1.19.0
parse-type==0.6.0
six==1.16.0
```

## .vscode/settings.json

```json
{
    "python.defaultInterpreterPath":"${workspaceFolder}/app/.venv/Scripts/python.exe",
    "python.terminal.activateEnvironment": true,
}
```

## app/features/my_feature.feature

```feature
Feature: Foo
    
    Scenario: Foo
        Given Plop
        When Ploop
        Then Ploooop
```

## app\features\steps\my_feature_steps.py

```py
from behave import given, when, then


@given("Plop")
def plop(context):
    print("Plop step executed")

@when("Ploop")
def ploop(context):
    print("Ploop step executed")

@then("Ploooop")
def ploooop(context):
    print("Ploooop step executed")
```

## Test Explorer Window

![image](https://user-images.githubusercontent.com/16876524/233003185-2e8bf405-7728-49a6-8f1b-7beacf5c940e.png)

## Extensions

[Test Explorer UI v2.21.1](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer)  
[Python Test Explorer for Visual Studio Code v0.7.1](https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter)  
[Behave Test Explorer v1.0.0](https://marketplace.visualstudio.com/items?itemName=YouneselBarnoussi.vscode-behave-test-adapter)  

## Where to go now?

I cannot see tests.  I am not sure what I need to put in place to run this extension so I can see the tests.

In the Test Explorer - there are two options: `Configure Python Tests` and `Install Additional Test Extensions...`.  If I click on `Configure Python Tests` then only `unittest` and `pytest` are displayed.

**Comment by YouneselBarnoussi** [comment]
Thanks for reporting this issues, the extension runs the `behave` command on root level of the workspace. In this case the `features` folder is found in `app` and not on the root level which means the behave command can't find any feature files.

I will think of a solution, and most likely add a config to state in which folder the `behave` command should be ran.

**Comment by andez2000** [comment]
OK thank you for the quick response.

In the mean time, I have:

1. Opened the `app` folder in VSCode 
2. moved my `.vscode` folder and changed interpreter to the new path

So the folder tree is now:

```
│   main.py
│   requirements.txt
│           
├───.venv
│           ...
├───.vscode
│       settings.json
│       
└───features
    │   my_feature.feature
    │   
    └───steps
            my_feature_steps.py
```

## .vscode/settings.json

```json
{
    "python.defaultInterpreterPath":"${workspaceFolder}/.venv/Scripts/python.exe",
    "python.terminal.activateEnvironment": true,
}
```

**Comment by YouneselBarnoussi** [comment]
Ah yes, currently the extension doesn't use the Python interpreter specified in `settings.json`, it uses the global installation. This is the same issue as #2.

I will try to fix and figure out how to use the interpreter path instead as this is a pretty big issue.

**Comment by andez2000** [comment]
Cool thanks.

Once behave is installed in the global pip packages:

![image](https://user-images.githubusercontent.com/16876524/233041391-859a1cb2-a9d0-4cb8-9c25-8335c19dd2c2.png)

I can now see the tests.  

Would be great to get fix to use the settings path.
