### ISSUE TITLE
Environment variables for behave tests triggered from the Test Explorer?

### ISSUE THREAD

**Issue by andez2000** [YouneselBarnoussi/vscode-BDD-Python-test-adapter#9]
I am getting a little different behaviour with the run and debug of a test that reads in an environment variable.

For simplicity `MY_ENV` is replacing the connection string.

## .vscode/launch.json

```json
{
    "configurations": [
        {
            "name": "Behave: Run all",
            "type": "python",
            "request": "launch",
            "module": "behave",
            "args": [
                "${workspaceFolder}/app/features"
            ],
            "env": {
                "MY_ENV": "smb",
            },
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

## powershell run

```console
$env:MY_ENV = "smb"
behave app/features
```

Not sure whether this is related to the Python Test UI or the Behave Test Adapter.

Python Test UI states that you can use the `settings.json` `"python.envFile": "${workspaceFolder}/test.env"` to specify a test environment.  This works when debugging - but not running.

Both of these approaches work - but only when I __debug__ a test from the Test Explorer.  If I click on __run__ alongside a test, it fails.

```
Scenario: Fooey  # app/features/my_feature.feature:3
    Given Plop     # app/features/steps/my_feature_steps.py:4
    When Ploop     # app/features/steps/my_feature_steps.py:8
      Traceback (most recent call last):
        File "c:\dev\code\playground\behave.next-issue\app\.venv\Lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "c:\dev\code\playground\behave.next-issue\app\.venv\Lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "app\features\steps\my_feature_steps.py", line 15, in ploop
          assert MY_ENV == "smb"
                 ^^^^^^^^^^^^^^^
```

## /app/features/steps/my_feature.py

```python
from behave import given, when, then
import os

@given("Plop")
def plop(context):
    print("Plop step executed")

@when("Ploop")
def ploop(context):
    print("Ploop step executed")

    MY_ENV = f"{os.getenv('MY_ENV')}"
    print(f"MY_ENV: {MY_ENV}")

    assert MY_ENV == "smb"

    print("ok")


@then("Ploooop")
def ploooop(context):
    print("Ploooop step executed")
```

## /.vscode/settings.json

```json
{
    "python.defaultInterpreterPath":"${workspaceFolder}/app/.venv/Scripts/python.exe",
    "python.terminal.activateEnvironment": true,
    "behaveTestAdapter.featuresFolderPath": "${workspaceFolder}/app/features",
    "python.envFile": "${workspaceFolder}/test.env"
}
```

## /test.env

```ini
MY_ENV=smb
```

Any thoughts on this one?

**Comment by andez2000** [comment]
In contrast to a `pytest` - this seems to work for a debug and a run - triggered from the Test Explorer

## /tests/test_variable.py

```python
import os

def test_variable_is_read():
    MY_ENV = f"{os.getenv('MY_ENV')}"
    print(f"MY_ENV: {MY_ENV}")

    assert MY_ENV == "smb"

    print("ok")
```

## /.vscode/settings.json

```json
{
    "python.defaultInterpreterPath":"${workspaceFolder}/app/.venv/Scripts/python.exe",
    "python.terminal.activateEnvironment": true,
    "python.testing.pyTestEnabled": true,
    "python.testing.pytestArgs": [
        "tests"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.envFile": "${workspaceFolder}/test.env"
}
```

## /test.env

```ini
MY_ENV="smb"
```

**Comment by YouneselBarnoussi** [comment]
The `debug` environment is run differently than the 'run' environment. Debugging is started using the vscode `API`, the vscode API loads all the settings from the `settings.json` file and that is why while running the debugger it works.

The `run` environment is used by creating a child process that runs the behave command, so this does not consider the `settings.json`.

At the moment, I haven't come up with an idea to fix it and I won't be available in the upcoming days. If you can provide me a solution using the command line, I can implement that easily but otherwise, I will have to do a bit more research.

**Comment by andez2000** [comment]
I'll have a look and try and spot something, thanks
